# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b83fbc80aa1ca26e63c9c09603f0ac8ec12e49b917024cb37b04cc19f5195d9f78aa59e748d11f4d2a42d47b4d64c4b4107de882db10082ec07b974707f4f1b

test:
  secret_key_base: 8c95911f4752634b06803e136d14ab752bf0777dde0fbd2645af4f5ffec45ecacd9a8f7c3f876892560031b5d408739939f03f13f40ab4d1d252b65c1ecd466f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
